# @format

name: Nodejs Ubuntu CI/CD
# triggers
on:
  push:
  pull_request:
  workflow_dispatch:

# workflow
jobs:
  # build app
  build:
    # simple description
    name: Build
    # runner os
    runs-on: ubuntu-latest
    # cache build artifacts
    steps:
      # check out repo
      - name: Checkout
        uses: actions/checkout@master
      # install node_modules
      - name: Install
        run: yarn install
      # build app
      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
      # archive production artifact for build step
      - name: Archive
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public

  # deploy app
  deploy:
    # simple description
    name: Deploy
    # requires build step to start
    needs: build
    # runner os
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - name: Checkout
        uses: actions/checkout@master
      # download build artifact
      - name: Download
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      # This command deploys your Hosting content and config to the following Firebase-provisioned subdomains:
      #
      # PROJECT_ID.web.app
      # PROJECT_ID.firebaseapp.com
      #
      # $ firebase deploy --only hosting
      #
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        # firebase token for deploy
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
